// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWKfNiZM007epE4bMcD4ffsHtjIRvNLs4',
    appId: '1:207297213062:web:774ecf254fbec7beacd707',
    messagingSenderId: '207297213062',
    projectId: 'chatapp-cf6c4',
    authDomain: 'chatapp-cf6c4.firebaseapp.com',
    storageBucket: 'chatapp-cf6c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzkikBCeuoNR_t7MsSJeIqCgrU9zRmYE',
    appId: '1:207297213062:android:b086461d6d686f61acd707',
    messagingSenderId: '207297213062',
    projectId: 'chatapp-cf6c4',
    storageBucket: 'chatapp-cf6c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfO_sWsX0eW975WubiTF78orWMwbtNHcw',
    appId: '1:207297213062:ios:b3518638cc00ec44acd707',
    messagingSenderId: '207297213062',
    projectId: 'chatapp-cf6c4',
    storageBucket: 'chatapp-cf6c4.appspot.com',
    iosClientId: '207297213062-i1g11st7o2i4t09r5ckfbp6l5tlq8qqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
